name: deploy UI to prod k8s

on:
  push:
    branches:
      - master
  pull_request:

env:
  GITHUB_REGISTRY: ghcr.io

jobs:
  build-image:
    name: Build and push service image  
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Build and push image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
          docker build -t $GITHUB_REGISTRY/tourmalinecore/inner-circle/auth-ui:latest -t $GITHUB_REGISTRY/tourmalinecore/inner-circle/auth-ui:${{ github.sha }} .
          docker push $GITHUB_REGISTRY/tourmalinecore/inner-circle/auth-ui:latest
          docker push $GITHUB_REGISTRY/tourmalinecore/inner-circle/auth-ui:${{ github.sha }}
  deploy-to-prod-k8s:
    needs: build-image
    name: Deploy service to k8s for prod environment  
    if: github.event_name == 'push'
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: |
            RELEASE_NAME=auth-ui
            helm repo add bitnami https://charts.bitnami.com/bitnami
            helm upgrade --install --namespace dev-inner-circle --create-namespace --values ./ci/values-custom.yaml \
            --set "image.tag=${{ github.sha }}" \
            --set "ingress.enabled=true" \
            --set "ingress.hostname=${{ secrets.DEV_HOST }}" \
            --set "extraConfigMapEnvVars.API_ROOT=${{ secrets.DEV_API_ROOT }}" \
            --set "extraConfigMapEnvVars.VITE_BASE_URL=${{ secrets.BASE_URL }}" \
            "${RELEASE_NAME}" \
            bitnami/nginx --version 15.0.2
          kubeconfig: "${{ secrets.DEV_KUBECONFIG }}"

e2e-test-prod:
    runs-on: ubuntu-22.04
    container: cypress/browsers:node-18.14.1-chrome-111.0.5563.146-1-ff-111.0.1-edge-111.0.1661.54-1
    needs: [deploy-to-prod]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: E2E test on prod
        uses: cypress-io/github-action@v5
        with:
          browser: electron
          record: true
          parallel: true
          group: "Electron e2e prod"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_BASE_URL: ${{ secrets.DEV_BASE_URL }}
          API_ROOT: '/api'
          VITE_BASE_URL: ${{ secrets.BASE_URL }}
          USER_LOGIN: ${{ secrets.DEV_USER_LOGIN }}
          USER_PASSWORD: ${{ secrets.DEV_USER_PASSWORD }}

      - name: Upload videos of tests failed 
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: |
            cypress/videos/*.mp4
            cypress/screenshots/**/*.png